//  GenerationStore.swift
//  State + history for the 创作 (image/video) panels. Mirrors ChatStore's async
//  task + @Published pattern and DictationHistoryStore's file persistence: the
//  generated bytes are archived under Application Support/generations/, and a
//  lightweight index (generations.json) records prompt/model/file per item. Cost
//  is recorded to the shared UsageStore (source "image"/"video").

import Foundation
import Combine

/// One finished generation (an image now; video in Phase B).
struct GeneratedItem: Identifiable, Codable, Hashable {
    var id: String
    var date: Date
    var kind: String          // "image" / "video"
    var prompt: String
    var modelLabel: String    // 渠道商/模型ID at generation time
    var fileName: String      // relative to the generations directory
    var revisedPrompt: String?

    var fileURL: URL { GenerationStore.directory.appendingPathComponent(fileName) }
}

@MainActor
final class GenerationStore: ObservableObject {
    @Published private(set) var items: [GeneratedItem] = []
    @Published var isGenerating = false
    @Published var lastError: String?

    private let settings: SettingsStore
    private let usage: UsageStore
    private var task: Task<Void, Never>?

    nonisolated static var directory: URL {
        SettingsStore.configDirectory().appendingPathComponent("generations", isDirectory: true)
    }
    private var indexURL: URL {
        SettingsStore.configDirectory().appendingPathComponent("generations.json")
    }
    private var saveWorkItem: DispatchWorkItem?

    init(settings: SettingsStore, usage: UsageStore) {
        self.settings = settings
        self.usage = usage
        try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
        load()
    }

    func items(kind: String) -> [GeneratedItem] { items.filter { $0.kind == kind } }

    // MARK: - Image generation

    func generateImage(model: ModelConfig, prompt: String, params: [String: String]) {
        let trimmed = prompt.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !isGenerating else { return }
        guard let resolved = settings.settings.resolve(model) else {
            lastError = "无法解析所选图像模型。"; return
        }
        isGenerating = true
        lastError = nil
        let label = settings.settings.displayLabel(for: model)
        task = Task { [weak self] in
            guard let self else { return }
            do {
                let assets = try await ImageClient.generate(resolved, prompt: trimmed, params: params)
                for asset in assets {
                    let id = UUID().uuidString
                    let name = "\(id).\(asset.ext)"
                    try? asset.data.write(to: Self.directory.appendingPathComponent(name), options: .atomic)
                    self.items.insert(GeneratedItem(
                        id: id, date: Date(), kind: "image", prompt: trimmed,
                        modelLabel: label, fileName: name, revisedPrompt: asset.revisedPrompt), at: 0)
                }
                // Per-call cost (image is billed per request; token usage n/a).
                self.usage.add(self.settings.settings.usageRecord(for: model, source: "image", date: Date()))
                self.save()
            } catch {
                if !Task.isCancelled && !(error is CancellationError) {
                    self.lastError = error.localizedDescription
                }
            }
            self.isGenerating = false
            self.task = nil
        }
    }

    func cancel() {
        task?.cancel()
        task = nil
        isGenerating = false
    }

    func remove(id: String) {
        if let item = items.first(where: { $0.id == id }) {
            try? FileManager.default.removeItem(at: item.fileURL)
        }
        items.removeAll { $0.id == id }
        save()
    }

    // MARK: - Persistence

    private func load() {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let data = try? Data(contentsOf: indexURL),
              let decoded = try? decoder.decode([GeneratedItem].self, from: data) else { return }
        items = decoded
    }

    private func save() {
        saveWorkItem?.cancel()
        let snapshot = items
        let url = indexURL
        let item = DispatchWorkItem {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            encoder.outputFormatting = [.prettyPrinted]
            guard let data = try? encoder.encode(snapshot) else { return }
            try? data.write(to: url, options: .atomic)
        }
        saveWorkItem = item
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.5, execute: item)
    }
}
